# Generated by Django 4.2 on 2023-04-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30)),
                ('building_location', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('building_picture', models.ImageField(blank=True, null=True, upload_to='static/img/building_picture/')),
            ],
            options={
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(choices=[('CSD', 'Computer Studies Department'), ('MD', 'Math Department')], max_length=3)),
                ('faculty_profile_picture', models.ImageField(blank=True, null=True, upload_to='static/img/facutly_prof_pic/')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=30)),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to='static/img/room_picture/')),
                ('building', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Building', to='timetable.building')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('student_id', models.CharField(help_text='Format: ####-##-#####', max_length=20, unique=True)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=15)),
                ('block', models.CharField(choices=[('Block 1', 'Block 1'), ('Block 2', 'Block 2'), ('Block 3', 'Block 3'), ('Block 4', 'Block 4')], max_length=10)),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], default=None, max_length=10)),
                ('student_profile_picture', models.ImageField(blank=True, null=True, upload_to='static/img/student_prof_pic/')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=30)),
                ('subject_title', models.CharField(max_length=30)),
                ('faculty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty', to='timetable.faculty')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='timetable.room')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(related_name='Students', to='timetable.student')),
                ('subjects', models.ManyToManyField(related_name='Subjects', to='timetable.subject')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
