# Generated by Django 4.2 on 2023-04-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_choice', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30)),
                ('building_location', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('building_picture', models.ImageField(blank=True, null=True, upload_to='static/img/building_picture/')),
            ],
            options={
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(choices=[('Computer Studies Department', 'Computer Studies Department'), ('Math Department', 'Math Department')], default=None, max_length=50)),
                ('faculty_profile_picture', models.ImageField(blank=True, null=True, upload_to='static/img/facutly_prof_pic/')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=30)),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to='static/img/room_picture/')),
                ('building', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Building', to='timetable.building')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Time',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choice', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Student Type',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_choice', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=30)),
                ('subject_title', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty', to='timetable.faculty')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='timetable.room')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('student_id', models.CharField(help_text='Format: ####-##-#####', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('student_profile_picture', models.ImageField(blank=True, null=True, upload_to='static/img/student_prof_pic/')),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Block', to='timetable.block')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='timetable.type')),
                ('year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Year', to='timetable.year')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='timetable.day')),
                ('end_time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endtime', to='timetable.time')),
                ('start_time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starttime', to='timetable.time')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='students', to='timetable.student')),
                ('subjects', models.ManyToManyField(blank=True, null=True, related_name='subjects', to='timetable.subject')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
