# Generated by Django 4.2 on 2023-04-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
    ]
