# Generated by Django 4.2 on 2023-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_choice',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_choice',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_choice',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
