# Generated by Django 4.2 on 2023-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_student_block_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSD', 'Computer Studies Department'), ('MD', 'Math Department')], default=None, max_length=3),
        ),
    ]
