# Generated by Django 4.2 on 2023-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_rename_start_time_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name_plural': 'Class Time'},
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(max_length=30),
        ),
    ]
