# Generated by Django 4.2 on 2023-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_time_options_alter_time_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
