# Generated by Django 4.2 on 2023-04-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_faculty_first_name_alter_faculty_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('Computer Studies Department', 'Computer Studies Department'), ('Math Department', 'Math Department')], default=None, max_length=50),
        ),
    ]
