# Generated by Django 4.2 on 2023-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_faculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_title',
            field=models.CharField(max_length=100),
        ),
    ]
