# Generated by Django 4.2 on 2023-04-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_time_options_alter_time_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='students',
        ),
        migrations.AddField(
            model_name='schedule',
            name='block_section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_section', to='timetable.block'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year_section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_section', to='timetable.year'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subjects',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='timetable.subject'),
        ),
    ]
