# Generated by Django 4.2 on 2023-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_schedule_students_schedule_block_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='projectsite\\static\\img\\student_prof_pic'),
        ),
    ]
