# Generated by Django 4.2 on 2023-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_schedule_students_schedule_block_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img/faculty_prof_pic/'),
        ),
    ]
