# Generated by Django 4.2 on 2023-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_student_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/student_prof_pic/'),
        ),
    ]
