# Generated by Django 4.2 on 2023-04-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_schedule_end_time_alter_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='timetable.student'),
        ),
    ]
