# Generated by Django 4.2 on 2023-04-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_schedule_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='students',
        ),
    ]
