# Generated by Django 4.2 on 2023-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_remove_schedule_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='timetable.student'),
        ),
    ]
