# Generated by Django 4.2 on 2023-04-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_alter_schedule_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='block_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_section', to='timetable.block'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty', to='timetable.faculty'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='timetable.room'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='timetable.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_section', to='timetable.year'),
        ),
    ]
