# Generated by Django 4.2 on 2023-04-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_room_inside_room_alter_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='inside_room',
        ),
    ]
