# Generated by Django 4.2 on 2023-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=None, max_length=10, null=True),
        ),
    ]
