# Generated by Django 4.2 on 2023-05-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(related_name='students', to='timetable.student'),
        ),
    ]
